service: serverless-open

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'
useDotenv: true # enable .env file support

provider:
  name: aws
  runtime: nodejs16.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  daisyChain:
    handler: handler.daisyChain
    events:
      - http:
          path: daisyChain
          method: get
  eventBridge:
    handler: handler.eventBridgeEvent
    events:
      - eventBridge:
          # leave the `eventBus` property empty to use the default AWS event bus
          # the event bus will be create / removed if it's a name. It will be attached to the event bridge if it's an arn
          pattern:
            source:
              - aws.cloudformation
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - cloudformation.amazonaws.com
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

